language: go
sudo: required
services:
  - docker
before_install:
- sudo apt-get -qqy update
- sudo mkdir -p misc/test/data/prouser/stor
- sudo mkdir -p misc/test/data/vsuser/stor
- sudo chmod -R 777 misc/test/data

script:
- make ci
go:
  - 1.10.2
cache:
  directories:
    misc/test/data
notifications:
  slack: pepabo:urThJPQ6Vh8m3cI7riDpYAbn
