max_connections = 10
idle_timeout = 60
transfer_timeout = 600
remote_addr = "127.0.0.1:21"

[tls]
cert = "./tls/server.crt"
key = "./tls/server.key"

[webapiserver]
uri = "http://127.0.0.1:8080/getDomain?username="