max_connections = 20
idle_timeout = 120
transfer_timeout = 600
remote_addr = "127.0.0.1:21"
proxy_protocol = false

[tls]
cert = "./tls/server.crt"
key = "./tls/server.key"

[webapiserver]
# %s replace by username on running
uri = "http://127.0.0.1:8080/getDomain?username=%s"
