max_connections = 10
idle_timeout = 60
transfer_timeout = 600
remote_addr = "127.0.0.1:21"

[tls]
cert = "./tls/server.crt"
key = "./tls/server.key"

[webapiserver]
url = "http://127.0.0.1"
port = "8080"
endpoint = "/getDomain"

