# ftpserver configuration file
#
# These are all the config parameters with their default values. If not present,

# Max number of control connections to accept
# max_connections = 0
base_dir = "./shared"
max_connections = 20

[server]
# Address to listen on
# listen_host = "0.0.0.0"
public_host = "127.0.0.1"

# Port to listen on
# listen_port = 2121

# Idle timeout time
# idle_timeout = 900

[server.dataPortRange]
start = 12122
end = 12200
