name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setupdir
      run: |
        sudo mkdir -p misc/test/data/prouser/stor
        sudo mkdir -p misc/test/data/vsuser/stor
        sudo chmod -R 777 misc/test/data

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: make ci
