name: pftp ci tester

on:
  pull_request:

jobs:
  release_action:
    name: pftp ci-test action
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
    - name: Set up Go 1.15.5
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.5
      id: go
    - name: Check out code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Execute ci-test
      if: github.event_name == 'pull_request'
      run: |
        make ci
