name: pftp ci tester

on:
  pull_request:

jobs:
  release_action:
    name: pftp ci-test action
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: prepare docker for testing
      run: |
        ./test/docker/setup_docker.sh
        ./test/docker/docker-entrypoint.sh bash
    - name: Execute ci-test
      if: github.event_name == 'pull_request'
      run: |
        CONTAINER_ID=$(uname -n)
        DIR_PREFIX=$(pwd | cut -d'/' -f1,2)
        DIR_SUFIX=$(pwd | cut -d'/' -f3-)
        SRC_PATH="$(docker inspect ${CONTAINER_ID} -f "{{ range .Mounts }}{{ if eq .Destination \"${DIR_PREFIX}\" }} {{ .Source }} {{end}}{{end}}" |sed "s/ //g")/${DIR_SUFIX}"
        make ci
