name: pftp ci tester

on:
  pull_request:

jobs:
  release_action:
    name: pftp ci-test action
    runs-on: ubuntu-latest
    container:
      image: heat1024/docker:golang1.15.5
    steps:
    - name: Update & install packages
      run: |
        apt-get -qq update
    - name: Check out code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Execute ci-test
      if: github.event_name == 'pull_request'
      run: |
        make ci
